# Generated by Django 4.2.6 on 2023-11-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_functie'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.functie'),
        ),
    ]
